version: "3.9"

services:
  web:
    build: .                # build từ Dockerfile trong thư mục hiện tại
    container_name: ngovihao-web
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6.2
    container_name: ngovihao-redis
